spring:
  application:
    name: election_system
  datasource:
    url: jdbc:mysql://localhost:3306/election_system
    username: root
    password: 2301
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
